# Generated by Django 4.2.11 on 2024-05-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_dataset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
