# Generated by Django 4.2.11 on 2024-05-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_topic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('queue', models.CharField(blank=True, max_length=50, null=True)),
                ('kwargs', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('current_state', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('log', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
