# Generated by Django 4.2.11 on 2024-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
