# Generated by Django 4.2.11 on 2024-07-11 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_history_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
