from config import default as df
from core.utils.env import get_env

# APP Configs
APP_MEDIA_ROOT = df.APP_MEDIA_ROOT

# Database Configs
DATABASE_ENGINE = get_env("DATABASE_ENGINE", df.DATABASE_ENGINE)
DATABASE_NAME = get_env("DATABASE_NAME", df.DATABASE_NAME)
DATABASE_USER = get_env("DATABASE_USER", df.DATABASE_USER)
DATABASE_PASSWORD = get_env("DATABASE_PASSWORD", df.DATABASE_PASSWORD)
DATABASE_HOST = get_env("DATABASE_HOST", df.DATABASE_HOST)
DATABASE_PORT = get_env("DATABASE_PORT", df.DATABASE_PORT, to="int")

# Celery Configs
CELERY_BROKER_URL = get_env("CELERY_BROKER_URL", df.CELERY_BROKER_URL)
CELERY_RESULT_BACKEND = get_env("CELERY_RESULT_BACKEND", df.CELERY_RESULT_BACKEND)

# Log Configs
LOG_STREAM_HANDLER_LEVEL = get_env("LOG_STREAM_HANDLER_LEVEL", df.LOG_STREAM_HANDLER_LEVEL)
LOG_STREAM_HANDLER_FORMAT = get_env("LOG_STREAM_HANDLER_FORMAT", df.LOG_STREAM_HANDLER_FORMAT)
LOG_FILE_HANDLER_NAME = get_env("LOG_FILE_HANDLER_NAME", df.LOG_FILE_HANDLER_NAME)
LOG_FILE_HANDLER_LEVEL = get_env("LOG_FILE_HANDLER_LEVEL", df.LOG_FILE_HANDLER_LEVEL)
LOG_FILE_HANDLER_FORMAT = get_env("LOG_FILE_HANDLER_FORMAT", df.LOG_FILE_HANDLER_FORMAT)
LOG_TASK_PARENT_DIR = df.LOG_TASK_PARENT_DIR
LOG_SERVER_PARENT_DIR = df.LOG_SERVER_PARENT_DIR

# Directory configs
MODELS_PATH = df.MODELS_PATH
CHROMA_PATH = df.CHROMA_PATH

# Model configs
EMBEDDING_MODEL_NAME = get_env("EMBEDDING_MODEL_NAME", df.EMBEDDING_MODEL_NAME)
RERANKER_MODEL_NAME = get_env("RERANKER_MODEL_NAME", df.RERANKER_MODEL_NAME)
LLM_MODEL_NAME = get_env("LLM_MODEL_NAME", df.LLM_MODEL_NAME)

# Knowledge storage and retrieval configs
HIDE_PII = get_env("HIDE_PII", df.HIDE_PII, to="bool")
REPLACE_PII_WITH_FAKE_DATA = get_env("REPLACE_PII_WITH_FAKE_DATA",
                                     df.REPLACE_PII_WITH_FAKE_DATA, to="bool")
PII_ENTITIES = get_env("PII_ENTITIES", df.PII_ENTITIES, to="list")
USE_CHAT_HISTORY_IN_CONTEXT = get_env("USE_CHAT_HISTORY_IN_CONTEXT",
                                      df.USE_CHAT_HISTORY_IN_CONTEXT, to="bool")

# Ollama configs
OLLAMA_URL = get_env("OLLAMA_URL", df.OLLAMA_URL)
